# Generated by Django 4.0.4 on 2022-06-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsletterrecipients_alter_article_editor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
